[versions]
agp = "9.4.0"
annotation = "1.10.0"
annotation-experimental = "1.6.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
media3 = "1.11.0"

[libraries]
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation"}
androidx-annotation-experimental = { group = "androidx.annotation", name = "annotation-experimental", version.ref = "annotation-experimental"}
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-media3-exo = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3"}
androidx-media3-effect = { group = "androidx.media3", name = "media3-effect", version.ref = "media3"}
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3"}

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
